name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal --collect 'XPlat Code Coverage' --settings coveralls.runsettings
    - run: |
        mkdir TestResults
        mv */TestResults/*/coverage.info TestResults/.
    - name: Publish Code Coverage
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./TestResults/coverage.info
    - name: Publish NuGet
      id: publish_nuget
      if: success() && github.event_name == 'push' && github.ref == 'refs/heads/master'
      uses: alirezanet/publish-nuget@v3.0.3
      with:
        PROJECT_FILE_PATH: AspNetCore.ReCaptcha/AspNetCore.ReCaptcha.csproj
        PACKAGE_NAME: AspNetCore.ReCaptcha
      env:
        NUGET_KEY: ${{ secrets.NUGET_KEY }}
    - name: Create release
      id: create_release
      if: success() && steps.publish_nuget.outputs.version != ''
      uses: actions/create-release@v1
      with:
        tag_name: ${{ steps.publish_nuget.outputs.version }}
        release_name: ${{ steps.publish_nuget.outputs.version }}
        body: ""
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
